name: topas2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1.0
  - r-readr=2.1.2
  - r-rlang=1.0.3
  - r-r.utils=2.11.0
  - r-igraph=1.2.11
  - r-dnet=1.1.7
  - bioconductor-biocparallel=1.28.0
  - r-dosnow=1.0.20
  - r-foreach=1.5.1
